selenium: &selenium
  working_directory: ~/studio
  docker:
    - image: tinganho/tingan.dev.env
    - image: elgalu/selenium
      shm_size: 1g
      privileged: true
      volumes:
        - /dev/shm:/dev/shm
      environment:
        SCREEN_WIDTH: 1280
        SCREEN_HEIGHT: 1000
      ports:
        - 4444:24444
        - 5901:25900

version: 2
jobs:
  build:
    <<: *devenv
    steps:
      - checkout

      - restore_cache:
          keys:
            - v{{ .Environment.CIRCLE_CACHE_VERSION }}-npm-lock-{{ .Branch }}-{{ .Environment.CIRCLE_JOB }}-{{ checksum "package-lock.json" }}
            - v{{ .Environment.CIRCLE_CACHE_VERSION }}-npm-lock-master-{{ .Environment.CIRCLE_JOB }}-{{ checksum "package-lock.json" }}
            - v{{ .Environment.CIRCLE_CACHE_VERSION }}-npm-cache-{{ .Branch }}-{{ .Environment.CIRCLE_JOB }}
            - v{{ .Environment.CIRCLE_CACHE_VERSION }}-npm-cache-master-{{ .Environment.CIRCLE_JOB }}

      - run:
          name: Install NPM Dependencies
          command: npm -v && npm install

      - run:
          name: Compile TypeScript Files
          command: tsc --version && tsc

      - run:
          name: Lint Files
          command: npm run lint

      - save_cache:
          key: v{{ .Environment.CIRCLE_CACHE_VERSION }}-npm-lock-{{ .Branch }}-{{ .Environment.CIRCLE_JOB }}-{{ checksum "package-lock.json" }}
          paths:
            - node_modules

      - save_cache:
          key: v{{ .Environment.CIRCLE_CACHE_VERSION }}-npm-cache-{{ .Branch }}-{{ .Environment.CIRCLE_JOB }}-{{ checksum "package-lock.json" }}
          paths:
            - /usr/local/share/.cache/npm
            - ~/.npm/_cacache

      - persist_to_workspace:
          root: .
          paths:
            - .