selenium: &selenium
  working_directory: ~/studio
  docker:
    - image: tinganho/tingan.dev.env
    - image: elgalu/selenium
      shm_size: 1g
      privileged: true
      volumes:
        - /dev/shm:/dev/shm
      environment:
        SCREEN_WIDTH: 1280
        SCREEN_HEIGHT: 1000
      ports:
        - 4444:24444
        - 5901:25900

version: 2
jobs:
  build:
    <<: *selenium
    steps:
      - checkout

      - run:
          name: Install NPM Dependencies
          command: npm -v && npm install

      - run:
          name: Test
          command: npm start
          